remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: [Rachel Kuzmich]
description: [remote sensing + ecology]

#make these show up at the top, for navigation
header_pages:
  - index.md
  - about.md
  - projects/index.md
  - blog.md
